### ISSUE TITLE
Provide arch & platform as vars to plugins

### ISSUE THREAD

**Issue by gilesw** [asdf-vm/asdf#1281]
### Is your feature request related to a problem? Please describe

Different project use different variations of these values. I've had to write code to handle it in each plugin so it would be nice to have some premade vars to save all that work.

### Describe the proposed solution

Include some globals for arch and platform with the ability to switch some on a per plugin basis

e.g
```
ASDF_ARCH_AMD=1

then if ARCH=x86_64 then ARCH=amd64

ASDF_PLATFORM_LCASE=1 then use lowercase PLATFORM var

```

### Describe similar `asdf` features and why they are not sufficient

nothing i'm aware of

### Describe other workarounds you've considered

various utils.bash files have custom code to do this.

**Comment by gilesw** [comment]
Now that I've actually built my own set of git binaries you might consider parsing .goreleaser.yml if it exists in the target repo as it may well contain things like this:-

```
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
```
