### ISSUE TITLE
asdf plugin-test fails with "asdf: command not found"

### ISSUE THREAD

**Issue by virtualstaticvoid** [asdf-vm/asdf#346]
### Steps to reproduce

Run tests on Travis CI with the following `.travis.yml` file for an asdf plugin such as [asdf-glooctl](https://github.com/virtualstaticvoid/asdf-glooctl).

E.g.

```yaml
language: c

script: asdf plugin-test glooctl https://github.com/virtualstaticvoid/asdf-glooctl.git

before_script:
  - git clone --branch v0.5.1 https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh

os:
  - linux
```

### Expected behavior

`asdf plugin-test` should pass.

### Actual behavior

Fails with `asdf/lib/commands/plugin-test.sh: line 47: asdf: command not found`.

See build logs from some of my plugins. E.g.

* [asdf-glooctl](https://travis-ci.org/virtualstaticvoid/asdf-glooctl/builds/413642318) 
* [asdf-helm](https://travis-ci.org/virtualstaticvoid/asdf-helm/builds/413642557)
* [asdf-istioctl](https://travis-ci.org/virtualstaticvoid/asdf-istioctl/builds/413643059)

### Environment

**OS**: linux - Ubuntu Trusty (Travis CI)

**asdf version**: v0.5.1

### Possible Fix

I experimented by removing the line `cd "$ASDF_DIR" || fail_test "could not cd $ASDF_DIR"
` from [lib/commands/plugin-test.sh#L45](https://github.com/asdf-vm/asdf/blob/master/lib/commands/plugin-test.sh#L45) and it behaves as expected.
