### ISSUE TITLE
Support passing a branch to the `plugin-test` command

### ISSUE THREAD

**Issue by mracos** [asdf-vm/asdf#385]
First of all, thanks for all the work on `asdf`, it is a really nice tool. :heart:

One use case where this feature would be really helpful is when testing changes from PRs on some sort of CI. Like here for example: halcyon/asdf-clojure#2

Maybe we can add another parameter and make `master` the default, what do you guys think?

**Comment by mracos** [comment]
Yep, reading the code I saw that we need to change the [`plugin-add`](https://github.com/asdf-vm/asdf/blob/master/lib/commands/plugin-add.sh#L31) command to support this since [`plugin-test`](https://github.com/asdf-vm/asdf/blob/master/lib/commands/plugin-test.sh#L51) uses it to add the plugin. 😞

But the tip you gave me worked, thanks! :heart:

[Here](https://travis-ci.org/mracos/asdf-clojure/builds/445773631) is an example of a build using the right repo and [here](https://travis-ci.org/mracos/asdf-clojure/builds/445773906) if the changes are wrong.

The final `travis.yml` is something like this (e.g. for the [halcyon/asdf-clojure](https://github.com/halcyon/asdf-clojure) plugin at least):

```yml
language: java
script:
  - asdf plugin-test clojure $TRAVIS_BUILD_DIR
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
  - git -C $TRAVIS_BUILD_DIR checkout $TRAVIS_BUILD_BRANCH
os:
  - linux
  - osx
```

Makes sense to add something like this to the [creating-plugins.md#testing-plugins](https://github.com/asdf-vm/asdf/blob/master/docs/creating-plugins.md#testing-plugins)?
