### ISSUE TITLE
`asdf plugin list` should return a 0 exit code when no plugins are installed

### ISSUE THREAD

**Issue by benfiola** [asdf-vm/asdf#903]
I'm using ansible to bootstrap a development environment.  Part of this process is installing asdf along with some plugins.  Prior to installing a plugin, I run `asdf plugin list` to see if that plugin is already installed.  When no plugins are installed, `asdf plugin list` will return a non-zero exit code - which ansible recognizes as a failure.  To me, having no plugins and attempting to list all installed plugins should just return an empty list - not a failure code.

It's not a big deal though - the workaround I'm doing is:

```
  - name: get asdf plugin list
    command: 
      cmd: "asdf plugin list"
    register: asdf_plugin_list
    failed_when: asdf_plugin_list.rc != 0 and 'No plugins installed' not in asdf_plugin_list.stderr
```

Buuut, I wouldn't mind throwing up a PR to address this if you're willing!
